language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "6"
  - "node"

script:
  - npm run eslint
  - npm run jscs
  - npm run test-cov

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master